package cfcc.com.shouChi.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "QUAN_BIE".
*/
public class QuanBieDao extends AbstractDao<QuanBie, Void> {

    public static final String TABLENAME = "QUAN_BIE";

    /**
     * Properties of entity QuanBie.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Scashclasscode = new Property(0, String.class, "scashclasscode", false, "SCASHCLASSCODE");
        public final static Property Scashclassname = new Property(1, String.class, "scashclassname", false, "SCASHCLASSNAME");
    }


    public QuanBieDao(DaoConfig config) {
        super(config);
    }
    
    public QuanBieDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"QUAN_BIE\" (" + //
                "\"SCASHCLASSCODE\" TEXT," + // 0: scashclasscode
                "\"SCASHCLASSNAME\" TEXT);"); // 1: scashclassname
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"QUAN_BIE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, QuanBie entity) {
        stmt.clearBindings();
 
        String scashclasscode = entity.getScashclasscode();
        if (scashclasscode != null) {
            stmt.bindString(1, scashclasscode);
        }
 
        String scashclassname = entity.getScashclassname();
        if (scashclassname != null) {
            stmt.bindString(2, scashclassname);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, QuanBie entity) {
        stmt.clearBindings();
 
        String scashclasscode = entity.getScashclasscode();
        if (scashclasscode != null) {
            stmt.bindString(1, scashclasscode);
        }
 
        String scashclassname = entity.getScashclassname();
        if (scashclassname != null) {
            stmt.bindString(2, scashclassname);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public QuanBie readEntity(Cursor cursor, int offset) {
        QuanBie entity = new QuanBie( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // scashclasscode
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // scashclassname
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, QuanBie entity, int offset) {
        entity.setScashclasscode(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setScashclassname(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(QuanBie entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(QuanBie entity) {
        return null;
    }

    @Override
    public boolean hasKey(QuanBie entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
